### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by pschyska** [mircearoata/SatisfactoryAreaActions#26]
Hey,

I tried to build this repo to customize the keybindings for flying.
I set up the template project as described in: https://docs.ficsit.app/satisfactory-modding/2.2.0/Development/BeginnersGuide/index.html. I.e. I set up the starter project (SML-Shipping-Dev-Win64.zip) and was able to compile.

Where do the contents of this repo go to? Am I supposed to add them to the starter project?

Opening FactoryGame.uproject from here in a fresh checkout didn't work. UE is complaining it needs to rebuild FactoryGame and fails. Also I'm unable to add WWise to this.

If I add the contents from here to the starter project, I'm not sure into which subdirectory, and what the mod directory settings in Alpakit should be.

**Comment by mircearoata** [comment]
Hmmm... I forgot to push the changes for SML 2.0, so the version here doesn't really work. I'll check if I even committed the version from before starting to rewrite the mod

**Comment by pschyska** [comment]
So, did you commit the changes :-)?
How's the rewrite coming along, anywhere we can track progress?

**Comment by mircearoata** [comment]
I hope the commit I just pushed had everything, but if it doesn't, at least you can build it with the latest SML.

[It's going well](https://streamable.com/7xfgyo), I have a few things left to do which I didn't write on the [public board](https://trello.com/b/YOudjl6r/area-actions) (some fixes and repairing existing AA 1.x buildings), and then UI. Blueprints are also technically half done by the copy action, but I might leave them for a future update, because it already took long enough

**Comment by yodax** [comment]
That looks amazing! Thanks for the mod

**Comment by pschyska** [comment]
Thank you! I'll check it out next week. The new structure looks like it would work.

**Comment by jml3on** [comment]
It's next week! :-)Any update?

**Comment by pschyska** [comment]
@jml3on I'm afraid I didn't end up working on this, sorry. I don't play the game at the moment.
Thanks for your efforts anyways @mircearoata!
Stay healthy.
